declare module 'grapesjs-tabs'
declare module 'grapesjs-component-countdown'
declare module 'grapesjs-custom-code'
declare module 'grapesjs-tooltip'
declare module 'grapesjs-typed'
declare module 'grapesjs-plugin-forms'
declare module 'grapesjs-blocks-basic'
declare module 'grapesjs-preset-webpage'